// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQQuclMaRZRjZ8zh9RDWvuIpOf-AjngV4',
    appId: '1:225286740730:web:6a26907833484cc8018743',
    messagingSenderId: '225286740730',
    projectId: 'waterup-3685d',
    authDomain: 'waterup-3685d.firebaseapp.com',
    storageBucket: 'waterup-3685d.appspot.com',
    measurementId: 'G-9G5RVKP9J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpBPRgMmGJr25uB6ylgHwPFm_Wxry1l-U',
    appId: '1:225286740730:android:78dea591cd1605c9018743',
    messagingSenderId: '225286740730',
    projectId: 'waterup-3685d',
    storageBucket: 'waterup-3685d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABzb_yWKPV9cKwd8Jlj6-Pm3LRO3KNyQA',
    appId: '1:225286740730:ios:092ac4dfbb745cf2018743',
    messagingSenderId: '225286740730',
    projectId: 'waterup-3685d',
    storageBucket: 'waterup-3685d.appspot.com',
    iosClientId: '225286740730-ne7eu4qf98c86a2ll1pi6hhja1rkgfcn.apps.googleusercontent.com',
    iosBundleId: 'waterlo.app',
  );
}
